frequency: 60
camera:
  camera_index: 1
  calibrate_image_path: ../assets
  ball:
    template_path: 
      - ../assets/ball_template.jpg
      - ../assets/ball_template1.jpg
      - ../assets/ball_template2.jpg
      - ../assets/ball_template3.jpg
      - ../assets/ball_template4.jpg
      - ../assets/ball_template5.jpg
      - ../assets/ball_template6.jpg
    boundary_points:
      - [0, 644]
      - [123, 421]
  robot:
    robot_a_aruco_id: 1
    robot_b_aruco_id: 2

  reward_condition:
    ball_reward:
      - [100, -0.01]
      - [1050, 0.01]
    done_reward:
      - [100, -1]
      - [1050, 1]
  done_condition:
    - 100
    - 1050
  coord_transformer:
    src_points:
      - [12, 404]
      - [634, 411]
      - [45, 133]
      - [604, 141]
    dst_points:
      - [0, 0]
      - [1150, 0]
      - [0, 548]
      - [1150, 548]
communication:
  car_a_ip: 192.168.0.201
  car_b_ip: 192.168.0.202
  client_ip: 127.0.0.1
  port: 5000
  server_ip: 192.168.0.203
